In [14]:
import numpy as np

In [15]:
matrix1 = np.array([
    [3, 1, 0, 0],
    [2, 2.5, 0.5, 0],
    [0, 0, 1, -0.5],
    [0, 0, 1.2, 2.0]
])

matrix2 = np.array([
    [1., 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])

matrix3 = np.array([
    [1.0, 0.24, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1.0, 0, 0, -0.2, 0, 0, 0, 0, 0],
    [0, -0.5, 1.0, 0, 0.05, 0, 0, 0, 0, 0],
    [0, 0, 0, 1.0, 0.1, 0, 0, 0, 0, 0],
    [0, 0.78, 0, 0, 1.0, 0, 0, 0, 0, 0],
    [0, 0, 0, -0.2, 0, 1.0, 0, 0, 0, 0],
    [0, 0, 0, 0.6, 0, 0, 1.0, -0.423, 0, 0],
    [0, 0, 0, 0, 0.05, 0, 0, 1.0, 0, 0],
    [0, 0, 0, 0, 0, 0.34, 0, 0, 1.0, 0.95],
    [0, 0, 0, 0, 0, 0, 0, 0, 0.95, 1.0]
])

b1 = np.array([4.3, 3.2, 2.2, 3.1])
b2 = np.array([-2.2, 12.5, -0.2, 3.1])
b3 = np.array([0.0, 1.0, 2.0, 4.0])
b4 = np.array([-9.9, 8.8, -7.7, 6.6, -5.5, 4.4, -3.3, 2.2, -1.1, 0.05])

In [16]:
# 4x4
print(np.linalg.solve(matrix1, b1))
print(np.linalg.solve(matrix1, b2))
print(np.linalg.solve(matrix1, b3))
print(np.linalg.solve(matrix2, b1))
print(np.linalg.solve(matrix2, b2))
print(np.linalg.solve(matrix2, b3))

# 10x10
print(np.linalg.solve(matrix3, b4))

[ 1.58076923 -0.44230769  2.28846154  0.17692308]
[-3.23251748  7.49755245  0.44230769  1.28461538]
[ 0.02797203 -0.08391608  2.30769231  0.61538462]
[4.3 3.2 2.2 3.1]
[-2.2 12.5 -0.2  3.1]
[0. 1. 2. 4.]
[-11.49861592   6.66089965  -3.83477509   7.66955017 -10.69550173
   5.93391003  -6.74492024   2.73477509 -32.46184012  30.88874811]
